#!/bin/sh

# install dependencies
# for macOS
# brew install tmux
# for Ubuntu
# sudo apt install tmux

# install tmux plugin manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# link tmux files
BASEDIR="$(cd "$( dirname "$0")" && pwd)"
ln -sf $BASEDIR/.tmux.conf ~/.tmux.conf
